export const allProjects = [
  {
    title: "Bookmarker",
    img: "./bookmarker-image.png",
    description: "description about Bookmarker",
    liveLink: "https://bookmarker.amanshahi.me/",
    githubRepoLink: "https://github.com/aman-shahi-dev/bookmarker",
    number: 1,
  },
  {
    title: "Shoppex",
    img: "./shoppex-image.png",
    description: "description about Bookmarker",
    liveLink: "https://aman-shahi-dev.github.io/shoppex/",
    githubRepoLink: "https://github.com/aman-shahi-dev/shoppex",
    number: 2,
  },
  {
    title: "Blog App",
    img: "./blog-app-image.png",
    description: "description about Bookmarker",
    liveLink: "https://blog-app-thebinarycoder.vercel.app/",
    githubRepoLink: "https://github.com/aman-shahi-dev/blog-app",
    number: 3,
  },
  {
    title: "Defender",
    img: "./defender-image.png",
    description: "description about Bookmarker",
    liveLink: "https://aman-shahi-dev.github.io/defender/",
    githubRepoLink: "https://github.com/aman-shahi-dev/defender",
    number: 4,
  },
  {
    title: "3D Button",
    img: "./3d-button-image.png",
    description: "description about 3D button",
    liveLink: "https://aman-shahi-dev.github.io/3d-button/",
    githubRepoLink: "https://github.com/aman-shahi-dev/3d-button",
    number: 5,
  },
];
